//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telenet.Carga.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telenet.Carga.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USE _NOME_BANCO_
        ///
        ///DECLARE @ERRO int
        ///DECLARE @MSG_ERRO varchar(512)
        ///
        ///EXEC [dbo].[CARGA_SOLICITA] 
        ///@ID_PROCESSO = &apos;&apos;_ID_PROCESSO_&apos;&apos;, 
        ///@ERRO = @ERRO OUTPUT, 
        ///@MSG_ERRO = @MSG_ERRO OUTPUT
        ///
        ///IF (@ERRO &gt; 0 AND (SELECT ERRO FROM CARGA_STATUS WHERE ID_PROCESSO = &apos;&apos;_ID_PROCESSO_&apos;&apos;) = 0)
        ///BEGIN
        ///	UPDATE CARGA_STATUS SET ERRO = @ERRO, MSG_ERRO = @MSG_ERRO, NIVEL = 100 WHERE ID_PROCESSO = &apos;&apos;_ID_PROCESSO_&apos;&apos;
        ///END
        ///
        ///IF (@ERRO = 666666)
        ///BEGIN
        ///	RAISERROR(@MSG_ERRO, 16, 1);
        ///END;.
        /// </summary>
        internal static string ScriptSolicitaCarga {
            get {
                return ResourceManager.GetString("ScriptSolicitaCarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USE _NOME_BANCO_
        ///
        ///DECLARE @ERRO int
        ///DECLARE @NUM_CARGA int
        ///DECLARE @VALOR_DA_CARGA numeric(15,2)
        ///DECLARE @CNPJ char(14)
        ///DECLARE @NOME_TABLE varchar(128)
        ///DECLARE @CODCLI int
        ///DECLARE @VALIDA_CPF_OUT char(1)
        ///DECLARE @MSG_ERRO varchar(512)
        ///
        ///EXEC [dbo].[CARGA_VALIDA_ARQUIVO]
        ///@DIRETORIO = &apos;&apos;_DIRETORIO_&apos;&apos;,
        ///@ARQUIVO = &apos;&apos;_NOME_ARQUIVO_&apos;&apos;,
        ///@CLIENTE_WEB = _CLIENTE_WEB_,
        ///@VALIDA_CPF = &apos;&apos;_VALIDA_CPF_&apos;&apos;,
        ///@LOGINOPE = &apos;&apos;_NOME_USUARIO_&apos;&apos;,
        ///@CODOPE = _CODIGO_OPERADORA_,
        ///@ORIGEM = &apos;&apos;_ORIGEM_&apos;&apos;,
        ///@NOME_ARQUIVO [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ScriptValidaArquivo {
            get {
                return ResourceManager.GetString("ScriptValidaArquivo", resourceCulture);
            }
        }
    }
}
