//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telenet.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telenet.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN
        ///	USE [msdb]
        ///
        ///	/****** Object:  Job [_JOB_NAME_]    Script Date: _CREATION_DATE_ ******/
        ///	BEGIN TRANSACTION
        ///
        ///	DECLARE @ReturnCode INT
        ///
        ///	SELECT @ReturnCode = 0
        ///
        ///	IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N&apos;[Uncategorized (Local)]&apos; AND category_class=1)
        ///	BEGIN
        ///		EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N&apos;JOB&apos;, @type=N&apos;LOCAL&apos;, @name=N&apos;[Uncategorized (Local)]&apos;
        ///
        ///		IF (@@ERROR &lt;&gt; 0 OR @ReturnCode &lt;&gt; 0) 
        ///			GOTO QuitWithRollback
        ///	END
        ///
        ///	DECLARE @jobId BINARY( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobTemplate {
            get {
                return ResourceManager.GetString("JobTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN 
        ///	USE [msdb]
        ///
        ///	/****** Object:  Job [_JOB_NAME_]    Script Date: _CREATION_DATE_ ******/
        ///	BEGIN TRANSACTION
        ///
        ///	DECLARE @ReturnCode INT
        ///
        ///	SELECT @ReturnCode = 0
        ///	
        ///	IF NOT EXISTS (SELECT name FROM msdb.dbo.syscategories WHERE name=N&apos;[Uncategorized (Local)]&apos; AND category_class=1)
        ///	BEGIN
        ///		EXEC @ReturnCode = msdb.dbo.sp_add_category @class=N&apos;JOB&apos;, @type=N&apos;LOCAL&apos;, @name=N&apos;[Uncategorized (Local)]&apos;
        ///
        ///		IF (@@ERROR &lt;&gt; 0 OR @ReturnCode &lt;&gt; 0) 
        ///			GOTO QuitWithRollback
        ///	END
        ///
        ///	DECLARE @jobId BINAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScheduledJobTemplate {
            get {
                return ResourceManager.GetString("ScheduledJobTemplate", resourceCulture);
            }
        }
    }
}
