BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'dbo' 
					 AND  TABLE_NAME = 'PAGNET_ESPECIEDOC')
	BEGIN
			DROP TABLE PAGNET_ESPECIEDOC
	END
END
BEGIN
    CREATE TABLE PAGNET_ESPECIEDOC
    (
         codEspecieDoc   INT NOT NULL PRIMARY KEY
        ,nmEspecieDoc    char(100)
    )
    
END
BEGIN

INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
    VALUES(1, 'DUPLICATA ')

END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(2, 'NOTA PROMISSÓRIA')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(3, 'APÓLICE / NOTA DE SEGURO')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(5, 'RECIBO')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(6, 'DUPLICATA DE SERVIÇO')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(7, 'LETRA DE CAMBIO')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(8, 'BDP - BOLETO DE PROPOSTA')
END
BEGIN
	INSERT INTO PAGNET_ESPECIEDOC (codEspecieDoc, nmEspecieDoc)
		VALUES(19, 'BCC – BOLETO CARTÃO DE CRÉDITO')

END