BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'dbo' 
					 AND  TABLE_NAME = 'PAGNET_INSTRUCAOCOBRANCA')
	BEGIN
			DROP TABLE PAGNET_INSTRUCAOCOBRANCA
	END
END
BEGIN
    CREATE TABLE PAGNET_INSTRUCAOCOBRANCA
    (
         codInstrucaoCobranca   INT NOT NULL PRIMARY KEY
        ,nmInstrucaoCobranca    char(100)
        ,bAtivo             BIT         NOT NULL DEFAULT 1
    )
    

END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(00, 'NÃO HÁ INSTRUÇÕES')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(2, 'BAIXAR APÓS QUINZE DIAS DO VENCIMENTO')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(3, 'BAIXAR APÓS 30 DIAS DO VENCIMENTO')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(4, 'NÃO BAIXAR')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(6, 'PROTESTAR')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(7, 'NÃO PROTESTAR')
END
BEGIN
	INSERT INTO PAGNET_INSTRUCAOCOBRANCA(codInstrucaoCobranca, nmInstrucaoCobranca)
		VALUES(8, 'NÃO COBRAR JUROS DE MORA')
END
