BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'dbo' 
					 AND  TABLE_NAME = 'PAGNET_TIPOCORRENCIAFALHA')
	BEGIN
			DROP TABLE PAGNET_TIPOCORRENCIAFALHA
	END
END
BEGIN
    CREATE TABLE PAGNET_TIPOCORRENCIAFALHA
    (
        CodTipOcorrenciaFalha   INT
       ,CodigoFalha             INT
       ,Descricao               nvarchar(250)
    )
END
BEGIN

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,4,'CONTA COBRANCA NAO NUMERICA')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,17,'CODI DA AGENCIA COBRADORA NAO NUMERICA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,42,'CONTA COBRANCA INVALIDA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,142,'NUM.AG.CEDENTE/DIG.NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,91,'TIPO/NÚMERO DE INSCRIÇÃO DO PAGADOR INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,143,'NUM. CONTA CEDENTE/DIG. NAO NUMERICO')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,371,'TITULO REJEITADO - OPERACAO DE DESCONTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(1,372,'TIT. REJEITADO - HORARIO LIMITE OP DESCONTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,10,'CODI PRIMEIRA INSTRUCAO NAO NUMERICA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,11,'CODI SEGUNDA INSTRUCAO NAO NUMERICA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,19,'NUMERO DO CEP NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,31,'INSTRUÇÃO RECUSADA PELO SISTEMA DE GARANTIAS ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,38,'MOVIMENTO EXCLUIDO POR SOLICITACAO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,65,'PEDIDO SUSTACAO JA SOLICITADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,67,'CLIENTE NAO TRANSMITE REG. DE OCORRENCIA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,77,'DESC. POR ANTEC. MAIOR/IGUAL VLR TITULO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(2,125,'COMPLEMENTO DA INSTRUCAO NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(3,0,'PAGAMENTO PARCIAL ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,39,'PERFIL NAO ACEITA TITULO EM BCO CORRESP')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,40,'COBR RAPIDA NAO ACEITA-SE BCO CORRESP')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,59,'INSTRUCAO ACEITA SO P/ COBRANCA SIMPLES ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,69,'PRODUTO DIFERENTE DE COBRANCA SIMPLES')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,170,'FORMA DE CADASTRAMENTO 2 INV.P.CART.5')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(4,201,'ALT.DO CONTR.PARTICIPANTEINVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(5,70,'DATA PRORROGACAO MENOR OUE DATA VENCTO')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(5,71,'DATA ANTECIPACAO MAIOR OUE DATA VENCTO')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(5,72,'DATA DOCUMENTO SUPERIOR A DATA INSTRUCAO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(5,88,'DATA INSTRUCAO INVALIDA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(6,18,'VALOR DO IOC NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(7,26,'CODI BANCO COBRADOR INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(7,41,'AGENCIA COBRADORA NAO ENCONTRADA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(8,130,'FORMA DE CADASTRAMENTO NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(8,131,'FORMA DE CADASTRAMENTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(8,132,'FORMA CADAST. 2 INVALIDA PARA CARTEIRA 3   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(8,133,'FORMA CADAST. 2 INVALIDA PARA CARTEIRA 4 ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(9,136,'CODI BCO NA COMPENSACAO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(9,137,'CODI BCO NA COMPENSACAO INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(10,140,'COD. SEOUEC.DO REG. DETALHE INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(10,141,'NUM. SEO. REG. DO LOTE NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(11,138,'NUM. LOTE REMESSA(DETALHE) NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(11,139,'TIPO DE REGISTRO INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(11,164,'NUMERO DO PLANO NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(12,202,'ALT. DO SEU NUMERO INVALIDA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(26,22,'CODI OCORRENCIA INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(26,134,'CODI DO MOV. REMESSA NAO NUMERICO  ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(28,1,'NOSSO NUMERO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(28,50,'NUMERO DO TITULO IGUAL A ZERO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(28,51,'TITULO NAO ENCONTRADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(28,92,'NOSSO NUMERO JA CADASTRADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(28,99,'REGISTRO DUPLICADO NO MOVIMENTO DIARIO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(31,5,'CODI DA CARTEIRA NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(31,6,'CODI DA CARTEIRA INVALIDO  ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(32,3,'DATA VENCIMENTO NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(32,16,'DATA DE VENCIMENTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(32,30,'DT VENC MENOR DE 15 DIAS DA DT PROCES   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(32,68,'TIPO DE VENCIMENTO INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(34,12,'VALOR DO TITULO EM OUTRA UNIDADE   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(34,13,'VALOR DO TITULO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(34,93,'VALOR DO TITULO NAO INFORMADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(34,94,'VALOR TIT. EM OUTRA MOEDA NAO INFORMADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(34,95,'PERFIL NAO ACEITA VALOR TITULO ZERADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,7,'ESPECIE DO DOCUMENTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,60,'ESPECIE DOCUMENTO NAO PROTESTAVEL   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,97,'ESPECIE DOCTO NAO PERMITE IOC ZERADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,129,'ESPEC DE DOCUMENTO NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,144,'TIPO DE DOCUMENTO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(36,145,'TIPO DE DOCUMENTO INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(39,15,'DATA EMISSAO NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(39,98,'DATA EMISSAO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(39,100,'DATA EMISSAO MAIOR OUE A DATA VENCIMENTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(41,149,'CODI DE MORA INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(41,150,'CODI DE MORA NAO NUMERICO  ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,14,'VALOR DE MORA NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,29,'VALOR DE MORA INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,109,'VALOR MORA TEM OUE SER ZERO (TIT = ZERO)   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,151,'VL.MORA IGUAL A ZEROS P. COD.MORA 1   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,152,'VL. TAXA MORA IGUAL A ZEROS P.COD MORA 2   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,153,'VL. MORA DIFERENTE DE ZEROS P.COD.MORA 3   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,154,'VL. MORA NAO NUMERICO P. COD MORA 2 ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(42,155,'VL. MORA INVALIDO P. COD.MORA 4 ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(44,86,'DATA SEGUNDO DESCONTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(44,87,'DATA TERCEIRO DESCONTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(44,110,'DATA PRIMEIRO DESCONTO INVALIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(44,111,'DATA DESCONTO NAO NUMERICA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,25,'VALOR DESCONTO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,74,'PRIM. DESNTO MAIOR/IGUAL VALOR TITULO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,75,'SEG. DESCONTO MAIOR/IGUAL VALOR TITULO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,76,'TERC. DESCONTO MAIOR/IGUAL VALOR TITULO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,77,'DESC. POR ANTEC. MAIOR/IGUAL VLR TITULO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,79,'NAO EXISTE PRIM. DESCONTO P/ CANCELAR   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,80,'NAO EXISTE SEG. DESCONTO P/ CANCELAR   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,81,'NAO EXISTE TERC. DESCONTO P/ CANCELAR   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,82,'NAO EXISTE DESC. POR ANTEC. P/ CANCELAR   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,90,'JA EXISTE DESCONTO POR DIA ANTECIPACAO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,112,'VALOR DESCONTO NAO INFORMADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(45,113,'VALOR DESCONTO INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(46,122,'VALOR IOF MAIOR OUE VALOR TITULO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(47,2,'VALOR DO ABATIMENTO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(47,114,'VALOR ABATIMENTO NAO INFORMADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(48,128,'CODI PROTESTO INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(48,146,'CODI P. PROTESTO NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(49,46,'QTD DE DIAS PROTESTO NAO PREENCHIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(49,147,'QTDE DE DIAS P. PROTESTO INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(49,148,'QTDE DE DIAS P. PROTESTO NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(52,45,'QTD DE DIAS DE BAIXA NAO PREENCHIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(52,156,'QTDE DIAS P.BAIXA/DEVOL. NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(52,157,'QTDE DIAS BAIXA/DEV. INVALIDO P. COD. 1   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(52,158,'QTDE DIAS BAIXA/DEV. INVALIDO P.COD. 2   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(52,159,'OTDE DIAS BAIXA/DEV.INVALIDO P.COD. 3 ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(53,8,'UNIDADE DE VALOR NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(53,9,'UNIDADE DE VALOR INVALIDA ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,24,'TOTAL PARCELA NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,27,'NUMERO PARCELAS CARNE NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,28,'NUMERO PARCELAS CARNE ZERADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,47,'TOT PARC. INF. NAO BATE Cl OTD PARC GER   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,48,'CARNE COM PARCELAS COM ERRO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,49,'SEU NUMERO NAO CONFERE COM O CARNE   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,162,'INDICADOR DE CARNE NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,163,'NUM. TOTAL DE PARC.CARNE NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,165,'INDICADOR DE PARCELAS CARNE INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,168,'N.TOT.PARC.INV.P.INDIC. MAIOR ZEROS   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(55,169,'NUM.TOT.PARC.INV.P.INDIC.DIFER.ZEROS ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(57,166,'N.SEO. PARCELA INV.P.INDIC. MAIOR 0   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(57,167,'N. SEO.PARCELA INV.P.INDIC.DIF.ZEROS ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,20,'TIPO INSCRICAO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,21,'NUMERO DO CGC OU CPF NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,58,'CGC/CPF INCORRETO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,105,'TIPO INSCRICAO NAO EXISTE   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,106,'CGCICPF NAO INFORMADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(59,108,'DIGITO CGC/CPF INCORRETO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(61,101,'NOME DO SACADO NAO INFORMADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(62,19,'NUMERO DO CEP NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(62,57,'CEP DO SACADO INCORRETO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(62,63,'CEP NAO ENCONTRADO NA TABELA DE PRACAS')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(62,123,'CEP DO SACADO NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(62,124,'CEP SACADO NAO ENCONTRADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(63,102,'ENDERECO DO SACADO NAO INFORMADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(63,160,'BAIRRO DO SACADO NAO INFORMADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(64,103,'MUNICIPIO DO SACADO NAO INFORMADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(65,104,'UNIDADE DA FEDERACAO NAO INFORMADA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(65,107,'UNIDADE DA FEDERACAO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(65,108,'DIGITO CGC/CPF INCORRETO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(66,161,'TIPO INSC.CPF/CGC SACADOR/AVAL.NAO NUM.   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(66,199,'TIPO INSC.CGC/CPF SACADOR.AVAL.INVAL. ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(67,200,'NUM.INSC.(CGC)SACADOR/AVAL.NAO NUMERICO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(71,84,'JA EXISTE SEGUNDO DESCONTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(74,85,'JA EXISTE TERCEIRO DESCONTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(76,89,'DATA MULTA MENOR/IGUAL OUE VENCIMENTO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(76,116,'DATA MULTA NAO NUMERICA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(76,118,'DATA MULTA NAO INFORMADA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(76,119,'DATA MULTA MAIOR OUE DATA DE VENCIMENTO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(77,83,'NAO EXISTE MULTA POR ATRASO P/ CANCELAR   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(77,120,'PERCENTUAL MULTA NAO NUMERICO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(77,121,'PERCENTUAL MULTA NAO INFORMADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(80,53,'OCOR. NAO ACATADA, TITULO BAIXADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(81,52,'OCOR. NAOACATADA,TITULO LIOUIDADO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(84,56,'OCOR. NAO ACATADA, TIT. NAO VENCIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(89,62,'SACADO NAO PROTESTAVEL ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(90,73,'ABATIMENTO MAIOR/IGUAL AO VALOR TITULO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(90,115,'VALOR ABATIMENTO MAIOR VALOR TITULO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(91,117,'VALOR DESCONTO MAIOR VALOR TITULO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(92,78,'NAO EXISTE ABATIMENTO P/ CANCELAR ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(93,43,'NAO BAIXAR, COMPL. INFORMADO INVALIDO ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,44,'NAO PROTESTAR, COMPL. INFORMADO INVALIDO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,54,'TITULO COM ORDEM DE PROTESTO JA EMITIDA   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,55,'OCOR. NAO ACATADA, TITULO JA PROTESTADO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,61,'CEDENTE SEM CARTA DE PROTESTO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,64,'TIPO DE COBRANCA NAO PERMITE PROTESTO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,66,'SUSTACAO PROTESTO FORA DE PRAZO   ')

	INSERT INTO PAGNET_TIPOCORRENCIAFALHA(CodTipOcorrenciaFalha,CodigoFalha,Descricao) VALUES(94,96,'ESPECIE DOCTO NAO PERMITE PROTESTO ')
END

