BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'dbo' 
					 AND  TABLE_NAME = 'PAGNET_CODIGOOCORRENCIA')
	BEGIN
			DROP TABLE PAGNET_CODIGOOCORRENCIA
	END
END
BEGIN
    CREATE TABLE PAGNET_CODIGOOCORRENCIA
    (
         CODOCORRENCIA   INT NOT NULL PRIMARY KEY
        ,NMOCORRENCIA    CHAR(100)
        ,ATIVO           CHAR(1)
    )
    
END
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(01 , 'ENTRADA DE TÍTULO', 'N')   
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(02 , 'BAIXA DE TÍTULO', 'S')   
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(04 , 'CONCESSÃO DE ABATIMENTO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(05 , 'CANCELAMENTO ABATIMENTO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(06 , 'ALTERAÇÃO DE VENCIMENTO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(07 , 'ALT. NÚMERO CONT.BENEFICIÁRIO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(08 , 'ALTERAÇÃO DO SEU NÚMERO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(09 , 'PROTESTAR', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(CODOCORRENCIA, NMOCORRENCIA, ATIVO)
    VALUES(10 , 'CONCESSÃO DE DESCONTO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(CODOCORRENCIA, NMOCORRENCIA, ATIVO)
    VALUES(11 , 'CANCELAMENTO DE DESCONTO', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(18 , 'SUSTAR PROTESTO (Após início do ciclo de protesto)', 'S')    
 
INSERT INTO PAGNET_CODIGOOCORRENCIA(codOcorrencia, nmOcorrencia, Ativo)
    VALUES(98 , 'NÃO PROTESTAR (Antes do início do ciclo de protesto)', 'S')
 
