BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'dbo' 
					 AND  TABLE_NAME = 'PAGNET_FORMAS_FATURAMENTO')
	BEGIN
			DROP TABLE PagNet_Formas_Faturamento
	END

END
BEGIN
    CREATE TABLE PAGNET_FORMAS_FATURAMENTO
    (
         CODFORMAFATURAMENTO        INT             NOT NULL  PRIMARY KEY
        ,NMFORMAFATURAMENTO         NVARCHAR(200) 
        ,ATIVO                      CHAR(1)
    )

END
BEGIN
     
 INSERT INTO PAGNET_FORMAS_FATURAMENTO(CODFORMAFATURAMENTO,NMFORMAFATURAMENTO,ATIVO)
    VALUES(1,'BOLETO','S')

END
BEGIN
 INSERT INTO PAGNET_FORMAS_FATURAMENTO(CODFORMAFATURAMENTO,NMFORMAFATURAMENTO,ATIVO)
    VALUES(2,'DEPÓSITO','S')


END
