BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_TAXAS_TITULOS')
	BEGIN
			DROP TABLE PagNet_Taxas_Titulos
	END
END
BEGIN
    CREATE TABLE PAGNET_TAXAS_TITULOS
    (
         CODTAXATITULO      INT             NOT NULL PRIMARY KEY
        ,CODTITULO          INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_EMISSAO_TITULOS(CODTITULO) 
        ,DESCRICAO          VARCHAR(200)    NOT NULL
        ,VALOR              DECIMAL(13,2)   NOT NULL     
        ,DTINCLUSAO         DATETIME        NOT NULL   
        ,ORIGEM             CHAR(2)         NOT NULL 
        ,CODUSUARIO         INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_USUARIO(CODUSUARIO) 
    )
END

