BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_LOGBOLETO')
	BEGIN
			DROP TABLE PAGNET_LOGBOLETO
	END
END
BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_LOGEMAILENVIADO')
	BEGIN
			DROP TABLE PAGNET_LOGEMAILENVIADO
	END

END
BEGIN
    CREATE TABLE PAGNET_LOGEMAILENVIADO
    (
         CODLOGEMAILENVIADO     INT                 NOT NULL  PRIMARY KEY
        ,CODUSUARIO             INT                 NOT NULL  FOREIGN KEY REFERENCES PAGNET_USUARIO(CODUSUARIO)
        ,CODCONTAEMAIL          INT                 NOT NULL  FOREIGN KEY REFERENCES PAGNET_CONTAEMAIL(CODCONTAEMAIL)
        ,CODEMISSAOBOLETO       INT                 NOT NULL  FOREIGN KEY REFERENCES PAGNET_EMISSAOBOLETO(CODEMISSAOBOLETO)
        ,EMAILDESTINO           VARCHAR(200)        NOT NULL
		,DTENVIO                DATETIME            NOT NULL
		,STATUS                 VARCHAR(250)        NOT NULL
		,MENSAGEM               VARCHAR(8000)       NOT NULL
    )

END