IF EXISTS (SELECT 1 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = 'DBO' 
                    AND  TABLE_NAME = 'PAGNET_PERFILACESSO')
BEGIN
        DROP TABLE PAGNET_PERFILACESSO
END
BEGIN
    CREATE TABLE PAGNET_PERFILACESSO
    (
         CODPERFILACESSO    INT             NOT NULL PRIMARY KEY
        ,CODEMPRESA         INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_CADEMPRESA(CODEMPRESA)
        ,NMPERFILACESSO     VARCHAR(70)     NOT NULL
        ,ATIVO              CHAR(1)       
    )
        
END
IF EXISTS (SELECT 1 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = 'DBO' 
                    AND  TABLE_NAME = 'PAGNET_ACESSOMENU')
BEGIN
        DROP TABLE PAGNET_ACESSOMENU
END
BEGIN
    CREATE TABLE PAGNET_ACESSOMENU
    (
         CODACESSOMENU      INT             NOT NULL PRIMARY KEY 
        ,CODPERFILACESSO    INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_PERFILACESSO(CODPERFILACESSO)
        ,CODMENU            INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_MENU(CODMENU)
        ,ATIVO              CHAR(1)       
    )
        
END
IF EXISTS (SELECT 1 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = 'DBO' 
                    AND  TABLE_NAME = 'PAGNET_ACESSOUSUARIO')
BEGIN
        DROP TABLE PAGNET_ACESSOUSUARIO
END
BEGIN
    CREATE TABLE PAGNET_ACESSOUSUARIO
    (
         CODACESSOUSUARIO   INT             NOT NULL PRIMARY KEY 
        ,CODPERFILACESSO    INT             NOT NULL FOREIGN KEY REFERENCES PAGNET_PERFILACESSO(CODPERFILACESSO)
        ,NIVELPERMISSAO     INT             NOT NULL 
        ,ATIVO              CHAR(1)       
    )
        
END