BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_CONFIG_REGRA_PAG')
	BEGIN
			DROP TABLE PagNet_Config_Regra_Pag
	END
END
BEGIN
    CREATE TABLE PAGNET_CONFIG_REGRA_PAG
    (
         CODREGRA               INT PRIMARY KEY NOT NULL          
        ,CODEMPRESA             INT FOREIGN KEY REFERENCES PAGNET_CADEMPRESA(CODEMPRESA)
        ,COBRATAXAANTECIPACAO   CHAR(1)         NOT NULL
        ,PERCTAXAANTECIPACAO    DECIMAL(15,2)     
        ,VLTAXAANTECIPACAO      DECIMAL(5,2)        
        ,FORMACOMPENSACAO       CHAR(1)         NOT NULL
        ,ATIVO                  CHAR(1)         NOT NULL

    )
END
BEGIN

	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_CONFIG_REGRA_PAG_LOG')
	BEGIN
			DROP TABLE PagNet_Config_Regra_Pag_Log
	END
END
BEGIN
		CREATE TABLE PAGNET_CONFIG_REGRA_PAG_LOG
		(
			 CODREGRA_LOG           INT   PRIMARY KEY      NOT NULL 
			,CODREGRA               INT                    NOT NULL     
			,CODEMPRESA             INT 
			,COBRATAXAANTECIPACAO   CHAR(1)         NOT NULL
			,PERCTAXAANTECIPACAO    DECIMAL(15,2)     
			,VLTAXAANTECIPACAO      DECIMAL(5,2)   
			,FORMACOMPENSACAO       CHAR(1)         NOT NULL
			,ATIVO                  CHAR(1)         NOT NULL
			,CODUSUARIO             INT             NOT NULL          
			,DATINCLOG              DATETIME        NOT NULL   
			,DESCLOG                VARCHAR(500)    NOT NULL

		)
END