BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_BORDERO_PAGAMENTO')
	BEGIN
			DROP TABLE PAGNET_BORDERO_PAGAMENTO
	END
END
BEGIN
    CREATE TABLE PAGNET_BORDERO_PAGAMENTO
    (
         CODBORDERO                     INT      NOT NULL PRIMARY KEY
        ,[STATUS]                       NVARCHAR(60) -- (PENDENTE / EM ANDAMENTO / PEND PAGAMENTO)
        ,CODUSUARIO                   	INT  NOT NULL  FOREIGN KEY REFERENCES PAGNET_USUARIO(CODUSUARIO)
        ,CODCONTACORRENTE              	INT  NOT NULL  FOREIGN KEY REFERENCES PAGNET_CONTACORRENTE(CODCONTACORRENTE)
        ,VLBORDERO                      DECIMAL(15,2)
        ,CODEMPRESA                     INT
        ,DTBORDERO                      DATETIME
    )

END

