
CREATE TABLE PAGNET_API_PGTO
(
    CODIGOAPI   INT             NOT NULL PRIMARY KEY,
    CAMINHO     VARCHAR(200)    NOT NULL,
    CODIGOBANCO NVARCHAR(6)     NOT NULL
)
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(1, 'API/PagNet/PGTOBradesco/', '237')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(2, 'API/PagNet/PGTOBrasil/', '001')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(3, 'API/PagNet/PGTOCEF/', '104')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(4, 'API/PagNet/PGTOItau/', '341')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(5, 'API/PagNet/PGTOSantander/', '033')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(6, 'API/PagNet/PGTOSafra/', '422')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(7, 'API/PagNet/PGTOSicredi/', '748')
GO
INSERT INTO PAGNET_API_PGTO(CODIGOAPI, CAMINHO, CODIGOBANCO)
VALUES(8, 'API/PagNet/PGTOSicoob/', '756')
