BEGIN
	IF EXISTS (SELECT 1 
					 FROM INFORMATION_SCHEMA.TABLES 
					 WHERE TABLE_SCHEMA = 'DBO' 
					 AND  TABLE_NAME = 'PAGNET_CADPLANOCONTAS')
	BEGIN
			DROP TABLE PagNet_CadPlanoContas
	END
END
BEGIN
    CREATE TABLE PAGNET_CADPLANOCONTAS
    (
         CODPLANOCONTAS         INT                 NOT NULL PRIMARY KEY
		,CODPLANOCONTAS_PAI     INT                     NULL 
        ,CODEMPRESA             INT                     NULL FOREIGN KEY REFERENCES PAGNET_CADEMPRESA(CODEMPRESA)
        ,CLASSIFICACAO          NVARCHAR(20)        NOT NULL
		,TIPO                   NVARCHAR(60)        NOT NULL
		,NATUREZA               NVARCHAR(60)        NOT NULL
        ,DESCRICAO              NVARCHAR(150)       NOT NULL    
        ,DESPESA                CHAR(1)             NOT NULL   
        ,DEFAULTPAGAMENTO       CHAR(1)             NOT NULL 
        ,DEFAULTRECEBIMENTO     CHAR(1)             NOT NULL
        ,PLANOCONTASDEFAULT     CHAR(1)             NOT NULL
        ,ATIVO                  CHAR(1)             NOT NULL        
    )

END

BEGIN
    INSERT INTO PAGNET_CADPLANOCONTAS (CODPLANOCONTAS,CODPLANOCONTAS_PAI,CODEMPRESA,CLASSIFICACAO,TIPO,NATUREZA,DESCRICAO,DESPESA,DEFAULTPAGAMENTO,DEFAULTRECEBIMENTO,PLANOCONTASDEFAULT,ATIVO)
    values (1,NULL, NULL,'1', 'Sinetica','Receita', 'Receita', 'N', 'N', 'S', 'S','S')

    INSERT INTO PAGNET_CADPLANOCONTAS (CODPLANOCONTAS,CODPLANOCONTAS_PAI,CODEMPRESA,CLASSIFICACAO,TIPO,NATUREZA,DESCRICAO,DESPESA,DEFAULTPAGAMENTO,DEFAULTRECEBIMENTO,PLANOCONTASDEFAULT,ATIVO)
    values (2,NULL, NULL,'1', 'Sinetica','Despesas', 'Despesas', 'S', 'S', 'N', 'S','S')

END